package com.example.hangmangame

class WordData {

    companion object{

        val hangmanDictionary = mapOf(
            "apple" to "A common fruit",
            "banana" to "A yellow tropical fruit",
            "chocolate" to "A sweet treat made from cocoa",
            "zebra" to "A black and white striped animal",
            "elephant" to "A large mammal with tusks",
            "guitar" to "A musical instrument with strings",
            "jazz" to "A genre of music",
            "ocean" to "A vast body of saltwater",
            "puzzle" to "A game or problem to solve",
            "kangaroo" to "A marsupial from Australia",
            "umbrella" to "Used for protection from rain",
            "parrot" to "A colorful tropical bird",
            "python" to "A large snake",
            "java" to "A programming language",
            "coffee" to "A popular caffeinated beverage",
            "rainbow" to "A spectrum of light in the sky",
            "lighthouse" to "A tall tower with a light to guide ships",
            "moonlight" to "Light from the moon",
            "butterfly" to "A flying insect with colorful wings",
            "sunflower" to "A tall, yellow flower",
            "starfish" to "A marine animal with five arms",
            "firefly" to "An insect that produces light",
            "waterfall" to "A cascade of water",
            "whale" to "A large marine mammal",
            "rocket" to "A vehicle that travels into space",
            "mountain" to "A large landform with steep sides",
            "sunset" to "The time when the sun disappears below the horizon",
            "campfire" to "A fire used for cooking or warmth",
            "sandcastle" to "A structure made of sand on the beach",
            "dragonfly" to "An insect with transparent wings",
            "dolphin" to "A marine mammal known for its intelligence",
            "mermaid" to "A mythical creature with the upper body of a human and the tail of a fish",
            "octopus" to "A marine animal with eight arms",
            "penguin" to "A flightless bird found in the Southern Hemisphere",
            "pineapple" to "A tropical fruit with a tough outer layer",
            "sunshine" to "Bright, direct sunlight",
            "watermelon" to "A juicy, refreshing fruit",
            "snowman" to "A figure made of snow with a carrot for a nose",
            "fireworks" to "Explosive devices that produce colorful displays",
            "snowflake" to "A unique ice crystal",
            "piano keys" to "The white and black keys on a piano",
            "giraffe neck" to "A long-necked mammal found in Africa",
            "bicycle ride" to "An activity involving a two-wheeled vehicle",
            "flamingo dance" to "A graceful bird known for its pink color",
            "carousel ride" to "A rotating platform with seats for amusement",
            "knight armor" to "Protective clothing worn by medieval warriors",
            "wizard hat" to "Pointed headgear worn by a magician",
            "robot dance" to "Mechanical movements performed by a machine",
            "spider web" to "A structure spun by a spider to catch prey",
            "cactus desert" to "A plant adapted to arid conditions",
            "breeze whispers" to "Soft sounds carried by the wind",
            "crystal clear" to "Completely transparent",
            "diamond ring" to "A precious gemstone set in jewelry",
            "wizard spell" to "Magical incantation cast by a sorcerer",
            "whisper wind" to "Soft sounds carried by the breeze",
            "knight sword" to "A weapon used by medieval warriors",
            "raven feather" to "A dark-colored bird's plumage",
            "cherry blossom" to "The flowers of a cherry tree",
            "valley view" to "A scenic vista in a low area between hills",
            "lemonade stand" to "A small business selling a refreshing drink",
            "peacock feather" to "A colorful plume from a peafowl",
            "fireball explosion" to "A powerful burst of flames",
            "voyage discovery" to "An adventurous journey of exploration",
            "treasure chest" to "A container holding valuable items",
            "cottage garden" to "A small house with a cultivated outdoor space",
            "dragon breath" to "The fiery exhalation of a mythical creature",
            "goblin mischief" to "Playful and mischievous behavior of a mythical creature",
            "mystic forest" to "An enchanted and mysterious wooded area",
            "mango fruit" to "A tropical and juicy fruit",
            "fairy wings" to "Delicate and magical appendages of a mythical being",
            "garden bloom" to "The colorful flowering of a cultivated outdoor space",
            "sorcerer hat" to "Headgear worn by a practitioner of magical arts",
            "thunderstorm" to "A weather phenomenon with thunder, lightning, and rain",
            "illusion magic" to "Deceptive and enchanting tricks performed by a magician",
            "serenade melody" to "A romantic and melodic musical composition",
            "unicorn horn" to "The mythical creature's spiraled appendage",
            "quasar glow" to "The luminous emission from a celestial object",
            "cosmic journey" to "An exploration of the vast universe",
            "galaxy cluster" to "A group of galaxies bound by gravity",
            "nebula swirl" to "A cloud of gas and dust in space with a spiral pattern",
            "enigma puzzle" to "A mysterious and challenging problem",
            "harmony melody" to "A pleasing arrangement of musical sounds",
            "whirlwind dance" to "A rapid and spinning movement",
            "twilight sky" to "The atmospheric condition between day and night",
            "jasmine fragrance" to "The sweet and aromatic scent of a flower",
            "elixir potion" to "A magical or medicinal liquid",
            "phoenix feather" to "A mythical bird's plumage known for rebirth",
            "cascade waterfall" to "A series of waterfalls",
            "enchant spell" to "A magical incantation to cast a spell",
            "harbor view" to "A scenic sight of a safe anchorage",
            "lagoon paradise" to "A beautiful and tranquil coastal area",
            "marvelous sight" to "An extraordinary and impressive view",
            "orchid bloom" to "The flowering of a delicate and exotic plant",
            "quiver arrow" to "A container for holding arrows",
            "silhouette shadow" to "A dark and outlined shadow",
            "tranquil scene" to "A peaceful and calm setting",
            "whisper secret" to "Softly spoken confidential information",
            "xylophone music" to "Melodic sounds produced by a musical instrument"
        )

        val hangmanList = hangmanDictionary.entries.toList()

        var hangmanDictionaryLength : Int = hangmanList.size

    }

}